SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '14/11/1995';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >=TO DATE ('14/11/1995', 'DD/MM/YY');
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO DATE ('11/14/1995', 'MM/DD/YY');
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO DATE ('11/14/1995', 'MM/DD/YY');
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 19 AND 22;