SELECT TC.NOME AS NOME_DO_CLIENTE, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE * INF.PRECO) as FATURAMENTO   
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN tabela_de_clientes TC
ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = 2021
AND TC.CPF = '1471156710'
GROUP BY TC.NOME, TP.NOME_DO_PRODUTO
ORDER BY TC.NOME, TP.NOME_DO_PRODUTO