SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;
SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;
SELECT NOME, CPF, CIDADE, BAIRRO FROM TABELA_DE_CLIENTES;
SELECT CPF AS IDENTIFICADOR, NOME AS, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES
SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;
SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", TDC.BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;
SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;