SELECT CPF, DATA_VENDA, NUMERO, IMPOSTO FROM notas_fiscais
WHERE MATRICULA = '00235' AND YEAR(DATA_VENDA) = 2020;


SELECT CPF, DATA_VENDA, NUMERO, IMPOSTO FROM notas_fiscais
WHERE MATRICULA =  '00235' AND YEAR(DATA_VENDA) = 2020
INTO OUTFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\notas_fiscais.csv'
FIELDS ENCLOSED BY '"' ESCAPED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n';


